import type { Metadata } from "next";
import localFont from "next/font/local";
import ThemeProvider from "../providers/ThemeProvider";
import GlobalStyles from "./globalStyles";
import { Box } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "100 900",
});
const cookierun = localFont({
  src: "./fonts/CookieRun-Regular.woff",
  variable: "--font-cookierun",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pretendard.variable} ${cookierun.variable} antialiased`}
      >
        <GlobalStyles />
        <ThemeProvider>
          <Box
            sx={{
              minWidth: "375px",
              width: "100%",
              minHeight: "100vh",
              overflow: "hidden",
              mx: "auto",
            }}
          >
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
