name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.bashrc || true
            source ~/.profile || true
            cd /home/projects/The-Wedding-Lab
            git fetch origin
            git reset --hard origin/main
            chmod +x ./deploy.sh
            bash ./deploy.sh
